// Sets up common environment for Shay Green's libraries.
// To change configuration options, modify blargg_config.h, not this file.

#ifndef BLARGG_ERR_H
#define BLARGG_ERR_H

typedef int blargg_err_t;

enum {
	ERR_FIRST = 1,
	ERR_ADDRESS_INVALID_INIT = ERR_FIRST,
	ERR_ADDRESS_INVALID_MUSIC,
	ERR_ADDRESS_INVALID_PLAY,
	ERR_BLIPBUF_RESIZE,
	ERR_DIGIMUSIC_NOT_SUPPORTED,
	ERR_EMU_INSTRUCTION_ILLEGAL,
	ERR_EOF,
	ERR_FASTPLAY_VALUE_INVALID,
	ERR_FILE_CANT_GET_SIZE,
	ERR_FILE_CANT_OPEN,
	ERR_FILE_CANT_READ,
	ERR_FILE_CANT_SEEK,
	ERR_FILE_CORRUPT,
	ERR_FILE_DATA_MISSING,
	ERR_FILE_NULL_PTR,
	ERR_FILE_WRONG_TYPE,
	ERR_GYM_PACKED_NOT_SUPPORTED,
	ERR_GZ_CANT_READ,
	ERR_GZ_CANT_SEEK,
	ERR_M3U_PLAYLIST_INVALID,
	ERR_M3U_TRACK_INVALID,
	ERR_MULTICHANNEL_NOT_SUPPORTED,
	ERR_OUT_OF_MEMORY,
	ERR_PLAYER_TYPE_NOT_SUPPORTED,
	ERR_READ,
	ERR_ROM_DATA_MISSING,
	ERR_SPC_EMULATION,
	ERR_TRACK_COUNT_INVALID,
	ERR_TRACK_DATA_MISSING,
	ERR_TRACK_INVALID,
	ERR_TRACK_SINGLE_ONLY,
	ERR_USE_FULL_EMULATOR_FOR_PLAYBACK,
	ERR_YM2413_FM_NOT_SUPPORTED,
	ERR_LAST = ERR_YM2413_FM_NOT_SUPPORTED
};

enum {
	WARN_FIRST = 1,
	WARN_ADDRESS_INVALID = WARN_FIRST,
	WARN_ADDRESS_INVALID_LOADINITPLAY,
	WARN_BANK_DATA_MISSING,
	WARN_BANK_INVALID,
	WARN_DATA_BAD_BLOCK_SIZE,
	WARN_DATA_HEADER_MISSING,
	WARN_DATA_SIZE_EXCESSIVE,
	WARN_EMU_INSTRUCTION_ILLEGAL,
	WARN_EXPANSION_HARDWARE_NOT_SUPPORTED,
	WARN_FILE_DATA_BLOCK_INVALID,
	WARN_FILE_DATA_MISSING,
	WARN_FILE_EXTRA_DATA,
	WARN_FILE_VERSION_UNKNOWN,
	WARN_FM_NOT_SUPPORTED,
	WARN_HEADER_DATA_UNKNOWN,
	WARN_M3U_AT_LINE,
	WARN_MULTIPLE_DATA_NOT_SUPPORTED,
	WARN_SCANLINE_INTERRUPT_NOT_SUPPORTED,
	WARN_SIZE_INVALID,
	WARN_STREAM_END_EVENT_MISSING,
	WARN_STREAM_EVENT_UNKNOWN,
	WARN_TIMER_MODE_INVALID,
	WARN_LAST = WARN_TIMER_MODE_INVALID
};

#endif
