name: Windows Build

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    name: Build on windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Zig
        uses: mlugg/setup-zig@v2

      - name: Build static library
        # avoid safe build on windows: https://github.com/ziglang/zig/issues/23138
        run: zig build --release=fast -Dlinkage=static

      - name: Build shared library
        run: zig build --release=fast -Dlinkage=dynamic
